### ISSUE TITLE
pip安装报错

### ISSUE THREAD

**Issue by dadanicholas** [HIT-SCIR/pyltp#104]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users>pip install pyltp
Collecting pyltp
  Using cached pyltp-0.1.9.1.tar.gz
Building wheels for collected packages: pyltp
  Running setup.py bdist_wheel for pyltp ... error
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
Exception:
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\pip\compat\__init__.py", li
ne 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 38: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\pip\basecommand.py", line 2
15, in main
    status = self.run(options, args)
  File "D:\Program Files\anaconda3\lib\site-packages\pip\commands\install.py", l
ine 342, in run
    prefix=options.prefix_path,
  File "D:\Program Files\anaconda3\lib\site-packages\pip\req\req_set.py", line 7
84, in install
    **kwargs
  File "D:\Program Files\anaconda3\lib\site-packages\pip\req\req_install.py", li
ne 878, in install
    spinner=spinner,
  File "D:\Program Files\anaconda3\lib\site-packages\pip\utils\__init__.py", lin
e 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "D:\Program Files\anaconda3\lib\site-packages\pip\compat\__init__.py", li
ne 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 38: invalid
 continuation byte

**Comment by FranNetty** [comment]
下载visualcpp那个编译工具编译一下试试
