### ISSUE TITLE
pip安装错误，win10 64位，anaconda 4.4.11，python 3.6.3

### ISSUE THREAD

**Issue by wuwujun** [HIT-SCIR/pyltp#147]
## 问题类型
pip安装错误
Failed building wheel for pyltp

## 代码片段
```
Exception:
Traceback (most recent call last):
  File "f:\anaconda\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 130: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\anaconda\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "f:\anaconda\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "f:\anaconda\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "f:\anaconda\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "f:\anaconda\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "f:\anaconda\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 130: invalid continuation byte
```
## 运行环境
win10 64位，anaconda 4.4.11，python 3.6.3
是否只能换成低版本anaconda

**Comment by liu946** [comment]
暂时不支持 anaconda 安装。
