### ISSUE TITLE
Ubuntu平台部署错误

### ISSUE THREAD

**Issue by zhangzhenwen** [HIT-SCIR/pyltp#72]
Internal Server Error: /demo/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zhangzw/WebSites/nlp/views.py", line 12, in analysis
    message = analyze(req_Text)
  File "/home/zhangzw/WebSites/nlp/process.py", line 12, in analyze
    words = segmentor.segment(content)
**## ArgumentError: Python argument types in
    Segmentor.segment(Segmentor, unicode)
did not match C++ signature:
    segment(Segmentor {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)**

**Comment by endyul** [comment]
参数需要是utf8编码
